routes/web.php
<?php

use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\LandingPageController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'auth.login');

Auth::routes([
    'register' => false,
]);



Route::middleware('auth')->group(function () {

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::middleware('admin')->group(function () {
        Route::resource('companies', CompanyController::class)->parameters([
            'companies' => 'company:slug',
        ]);
        Route::resource('employees', EmployeeController::class)->except(['show']);
        Route::get('employees/{company:slug}', [EmployeeController::class, 'show'])->name('employees.show');
    });
});

app/Models/Company.php
<?php

namespace App\Models;

use Spatie\MediaLibrary\HasMedia;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Spatie\MediaLibrary\InteractsWithMedia;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class Company extends Model implements HasMedia
{
    use HasFactory;
    use InteractsWithMedia;
    use SoftDeletes;
    use Notifiable;

    protected $fillable = ['name', 'slug', 'email', 'website'];

    public static function availableCompany()
    {
        return static::pluck('id')->toArray();
    }

    public function employees()
    {
        return $this->hasMany(Employee::class);
    }

    // image conversion
    // public function registerMediaConversions(Media $media = null): void
    // {
    //     $this->addMediaConversion('thumb')
    //         ->width(180)
    //         ->height(180)
    //         ->performOnCollections('company-logo');
    // }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Models\Company;
use Illuminate\Support\Str;
use App\DataTables\CompanyDataTable;
use App\Http\Requests\CompanyRequest;
use App\Http\Requests\UpdateCompanyRequest;
use App\Models\Employee;
use App\Services\CompanyService;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(CompanyDataTable $dataTable)
    {
        return $dataTable->render('companies.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('companies.create', [
            'company' => new Company(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request\CompanyRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CompanyRequest $request)
    {
        (new CompanyService())->createCompany($request);

        session()->flash('success', __('Company has been created.'));
        return redirect('companies');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company, Employee $employee)
    {
        $company->load('employees');
        return view('companies.show', [
            'company' => $company,
            'employeeCount' => $company->employees()->count(),
            'menu' => 'companies',
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        return view('companies.edit', compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request\UpdateCompanyRequest  $request
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCompanyRequest $request, Company $company)
    {
        $company->update($request->validated());
        (new CompanyService())->updateImg($company, $request);

        session()->flash('success', __('Company has been updated.'));
        return redirect('companies');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
        $company->delete();
        $company->media()->delete();
        session()->flash('success', __('Company has been deleted.'));
        return redirect('companies');
    }
}

resources/views/companies/partials/_form-control.blade.php
    <div class="form-group">
        <label for="name">{{ __('Company Name') }}</label>
        <input type="text" name="name" id="name" class="form-control @error('name') is-invalid @enderror"
            value="{{ old('name') ?? $company->name }}" placeholder="ex: GR Tech Company">

        @error('name')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
    </div>

    <div class="form-group">
        <label for="email">{{ __('Email') }}</label>
        <input type="email" name="email" id="email" class="form-control @error('email') is-invalid @enderror"
            value="{{ old('email') ?? $company->email }}" placeholder="ex: mail@grtech.com.my">

        @error('email')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
    </div>


    <div class="form-group">
        <label for="website">{{ __('Website') }}</label>
        <input type="text" name="website" id="website" class="form-control @error('website') is-invalid @enderror"
            value="{{ old('website') ?? $company->website }}" placeholder="www.example.com">

        @error('website')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
    </div>



    <div class="form-group">


        @if (request()->segment(2) == 'create')
            <label for="img">Logo</label>
            <div class="custom-file">
                <input type="file" name="img" class="custom-file-input" id="img">
                <label class="custom-file-label" for="img">Choose file</label>
            </div>
    </div>
@else

    <div class="form-group">
        <label for="img">Logo</label>
        <input type="file" name="img" id="img" class="form-control">
    </div>

    @endif


    @if ($company->getFirstMediaUrl('company-logo'))
        <center> <img src="{{ $company->getFirstMediaUrl('company-logo') }}" alt="" class="img-fluid w-50"></center>
    @endif

resources/views/companies/partials/action.blade.php
<x-dropdown>
    <a href="{{ route('companies.show', $company->slug) }}" class="dropdown-item"
        title="{{ __('Company detail.') }}"><i class="far fa-eye nav-icon"></i>
        {{ __('Detail') }}
    </a>

    <button type="button" class="dropdown-item" title="{{ __('Edit Company.') }}" data-toggle="modal"
        data-target="#{{ $company->slug }}">
        <i class="fas fa-edit nav-icon"></i>
        {{ __('Edit') }}
    </button>


    <form action="{{ route('companies.destroy', $company->slug) }}" method="post" class="d-inline">
        @csrf
        @method('delete')
        <button class="dropdown-item" title="{{ __('Delete Company.') }}" type="submit"
            onclick="return confirm('Are you sure want to delete this company?')">
            <i class="fas fa-trash nav-icon"></i>
            {{ __('Delete') }}
        </button>
    </form>


    <!-- Button trigger modal -->


</x-dropdown>

<!-- Modal Edit -->
<div class="modal fade" id="{{ $company->slug }}" tabindex="-1" aria-labelledby="{{ $company->slug }}Label"
    aria-hidden="true">
    <div class="modal-dialog ">
        <form action="{{ route('companies.update', $company->slug) }}" method="post" class="d-inline"
            enctype="multipart/form-data">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="{{ $company->slug }}Label">Edit {{ $company->name }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                @csrf
                @method('patch')
                <div class="modal-body text-left">
                    @include('companies.partials._form-control')
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn bg-orange">Update Company</button>
                </div>
        </form>
    </div>
</div>

resources/views/companies/partials/logo.blade.php
@if ($company->getFirstMediaUrl('company-logo'))
    <a href="{{ asset($company->getFirstMediaUrl('company-logo')) }}" data-toggle="lightbox" data-gallery="gallery">
        <div class="logo-image-thumb">
            <img src="{{ $company->getFirstMediaUrl('company-logo') }}" alt="{{ $company->slug }}-logo"
                class="img img-thumbnail w-75">
        </div>
    </a>

@endif

resources/views/companies/partials/website.blade.php
<a href="//{{ $company->website }}">{{ $company->website }}</a>