routes/web.php
<?php

use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\LandingPageController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'auth.login');

Auth::routes([
    'register' => false,
]);



Route::middleware('auth')->group(function () {

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::middleware('admin')->group(function () {
        Route::resource('companies', CompanyController::class)->parameters([
            'companies' => 'company:slug',
        ]);
        Route::resource('employees', EmployeeController::class)->except(['show']);
        Route::get('employees/{company:slug}', [EmployeeController::class, 'show'])->name('employees.show');
    });
});

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Employee extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = ['first_name', 'last_name', 'company_id', 'email', 'phone'];

    public function fullname()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function company()
    {
        return $this->belongsTo(Company::class);
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Company;
use App\Models\Employee;
use Illuminate\Http\Request;
use App\DataTables\EmployeeDataTable;
use App\Events\EmployeeCreated;
use App\Http\Requests\EmployeeRequest;
use App\Http\Requests\UpdateEmployeeRequest;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(EmployeeDataTable $dataTable)
    {
        return $dataTable->render('employees.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('employees.create', [
            'employee' => new Employee(),
            'companies' => Company::pluck('name', 'id'),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request\EmployeeRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EmployeeRequest $request)
    {
        $attr = $request->validated();
        $attr['company_id'] = $request->company;
        $employees = Employee::create($attr);

        event(new EmployeeCreated($employees));

        session()->flash('success', __('Employee has been created.'));
        return redirect('employees');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        $company->with('employees');
        return view('companies.show', [
            'company' => $company,
            'employeeCount' => $company->employees()->count(),
            'menu' => 'employees',
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request\EmployeeRequest  $request
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateEmployeeRequest $request, Employee $employee)
    {
        $attr = $request->validated();
        $attr['company_id'] = $request->company;
        $employee->update($attr);
        session()->flash('success', __('Employee has been updated.'));
        return redirect('employees');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        $employee->delete();
        session()->flash('success', __('Employee has been deleted.'));
        return redirect('employees');
    }
}

resources/views/employees/partials/_form-control.blade.php
<div class="form-group">
    <label for="company">Company</label>
    <select name="company" id="company" class="form-control select2 @error('company') is-invalid @enderror">
        @if ($employee->company_id)
            <option value="{{ $employee->company_id }}">{{ $employee->company->name }}</option>

            @foreach ($companies as $id => $name)
                <option value="{{ $id }}">{{ $name }}</option>
            @endforeach
        @else
            <option value="" selected>Select a Company</option>
            @foreach ($companies as $id => $name)
                <option value="{{ $id }}">{{ $name }}</option>
            @endforeach
        @endif
    </select>

    @error('company')
        <span class="invalid-feedback" role="alert">{{ $message }}</span>
    @enderror
</div>

<div class="form-group">
    <label for="first_name">First Name</label>
    <input type="text" name="first_name" id="first_name" class="form-control @error('first_name') is-invalid @enderror"
        value="{{ old('first_name') ?? $employee->first_name }}" placeholder="ex: Jhon">

    @error('first_name')
        <span class="invalid-feedback" role="alert">{{ $message }}</span>
    @enderror
</div>

<div class="form-group">
    <label for="last_name">Last Name</label>
    <input type="text" name="last_name" id="last_name" class="form-control @error('last_name') is-invalid @enderror"
        value="{{ old('last_name') ?? $employee->last_name }}" placeholder="ex: Doe">

    @error('last_name')
        <span class="invalid-feedback" role="alert">{{ $message }}</span>
    @enderror
</div>

<div class="form-group">
    <label for="email">Email</label>
    <input type="email" name="email" id="email" class="form-control @error('email') is-invalid @enderror"
        value="{{ old('email') ?? $employee->email }}" placeholder="ex: example@mail.com">

    @error('email')
        <span class="invalid-feedback" role="alert">{{ $message }}</span>
    @enderror
</div>

<div class="form-group">
    <label for="phone">Phone</label>
    <input type="number" name="phone" id="phone" class="form-control @error('phone') is-invalid @enderror"
        value="{{ old('phone') ?? $employee->phone }}" placeholder="ex: 601234567">

    @error('phone')
        <span class="invalid-feedback" role="alert">{{ $message }}</span>
    @enderror
</div>

resources/views/employees/partials/action.blade.php
<x-dropdown>

    <button type="button" class="dropdown-item" title="{{ __('Edit Employee.') }}" data-toggle="modal"
        data-target="#employee-{{ $employee->id }}">
        <i class="fas fa-edit nav-icon"></i>
        {{ __('Edit') }}
    </button>


    <form action="{{ route('employees.destroy', $employee->id) }}" method="post" class="d-inline">
        @csrf
        @method('delete')
        <button class="dropdown-item" title="{{ __('Delete Company.') }}" type="submit"
            onclick="return confirm('Are you sure want to delete this employee?')">
            <i class="fas fa-trash nav-icon"></i>
            {{ __('Delete') }}
        </button>
    </form>




</x-dropdown>

<!-- Modal Edit -->
<div class="modal fade" id="employee-{{ $employee->id }}" tabindex="-1" aria-labelledby="{{ $employee->id }}Label"
    aria-hidden="true">
    <div class="modal-dialog ">
        <form action="{{ route('employees.update', $employee->id) }}" method="post" class="d-inline"
            enctype="multipart/form-data">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="{{ $employee->id }}Label">Edit {{ $employee->fullname() }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                @csrf
                @method('patch')
                <div class="modal-body text-left">
                    @include('employees.partials._form-control')
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn bg-orange">Update Employee</button>
                </div>
        </form>
    </div>
</div>

resources/views/employees/partials/company.blade.php
<a href="{{ route('employees.show', $employee->company->slug) }}">{{ $employee->company->name }}</a>