routes/web.php
<?php

use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\LandingPageController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'auth.login');

Auth::routes([
    'register' => false,
]);



Route::middleware('auth')->group(function () {

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::middleware('admin')->group(function () {
        Route::resource('companies', CompanyController::class)->parameters([
            'companies' => 'company:slug',
        ]);
        Route::resource('employees', EmployeeController::class)->except(['show']);
        Route::get('employees/{company:slug}', [EmployeeController::class, 'show'])->name('employees.show');
    });
});

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Employee extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = ['first_name', 'last_name', 'company_id', 'email', 'phone'];

    public function fullname()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function company()
    {
        return $this->belongsTo(Company::class);
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Company;
use App\Models\Employee;
use Illuminate\Http\Request;
use App\DataTables\EmployeeDataTable;
use App\Events\EmployeeCreated;
use App\Http\Requests\EmployeeRequest;
use App\Http\Requests\UpdateEmployeeRequest;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(EmployeeDataTable $dataTable)
    {
        return $dataTable->render('employees.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('employees.create', [
            'employee' => new Employee(),
            'companies' => Company::pluck('name', 'id'),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request\EmployeeRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EmployeeRequest $request)
    {
        $attr = $request->validated();
        $attr['company_id'] = $request->company;
        $employees = Employee::create($attr);

        event(new EmployeeCreated($employees));

        session()->flash('success', __('Employee has been created.'));
        return redirect('employees');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        $company->with('employees');
        return view('companies.show', [
            'company' => $company,
            'employeeCount' => $company->employees()->count(),
            'menu' => 'employees',
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request\EmployeeRequest  $request
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateEmployeeRequest $request, Employee $employee)
    {
        $attr = $request->validated();
        $attr['company_id'] = $request->company;
        $employee->update($attr);
        session()->flash('success', __('Employee has been updated.'));
        return redirect('employees');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        $employee->delete();
        session()->flash('success', __('Employee has been deleted.'));
        return redirect('employees');
    }
}

resources/views/employees/create.blade.php
@extends('layouts.app',[
'page' => 'Create Employee',
'title' => 'Create Employee'
])

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('employees.index') }}">Employees</a></li>
    <li class="breadcrumb-item active">{{ __('Create') }}</li>
@endsection

@section('content')
    <x-alert />
    <div class="row">
        <div class="col-md-10">
            <div class="card">

                <form action="{{ route('employees.store') }}" method="post">
                    @csrf
                    <div class="card-body">
                        @include('employees.partials._form-control')
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">{{ __('Create') }}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/employees/index.blade.php
@extends('layouts.app',[
'page' => 'Employees',
'title' => 'Employees'
])

@section('breadcrumb')
    <li class="breadcrumb-item active">Employees</li>
@endsection

@section('content')
    <div class="d-flex justify-content-center">
        <div class="col-md-10">
            <a href="{{ route('employees.create') }}" class="btn bg-orange mb-4">{{ __('Add Employee') }}</a>
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">{{ $tableHeader ?? 'Employees Table' }}</h3>


                </div>

                <div class="card-body table-responsive ">
                    {!! $dataTable->table([
    'class' => 'table table-centered table-striped dt-responsive
        nowrap w-100',
    'id' => 'employee-table',
]) !!}
                </div>
                <!-- /.card-header -->

                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>

    </div>



@endsection

@push('script')
    {!! $dataTable->scripts() !!}
    @if ($errors->any())
        @foreach ($errors->all() as $messages)
            @php
                $message[] = $messages;
            @endphp
        @endforeach

        <script>
            $(document).ready(function() {
                Swal.fire({
                    icon: 'error',
                    title: 'Failed to update!',
                    text: '{!! join('-<br>', $message) !!}',
                });
            });
        </script>

    @endif
@endpush